### ISSUE TITLE
Space between table cells

### ISSUE THREAD

**Issue by boringer** [boringer/note#6]
```html
<table>
    <thead>
        <tr>
            <th>Heading 1</th>
            <th>Heading 2</th>
            <th>Heading 3</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Cell 1</td>
            <td>Cell 2</td>
            <td>Cell 3</td>
        </tr>
        <tr>
            <td>Cell 4</td>
            <td>Cell 5</td>
            <td>Cell 6</td>
        </tr>
    </tbody>
</table>
```

```css
table {
    border-spacing: 1em 0.5em;
}
th,
td {
    border: 1px solid;
}
```

It looks like this (only with `border-collapse: separate`):

![_users_boring_my_work_study_code_note_6 html](https://user-images.githubusercontent.com/14685751/36943332-a6864dbe-1fc2-11e8-99f1-23219a0e4ef1.png)
